---
# vi: ts=2 sw=2 et:

name: Feature request
description: Suggest an improvement
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: The rtpengine version you checked that didn't have the feature you are asking for
      description: If this is not the most recently released upstream version, then please check first if it has that feature already.
      placeholder: '12.2.0.0+0~mr12.2.0.0+0~20231205160601.20604+bookworm~1.gbpa75a82'
    validations:
      required: false
